graph TD
    A[SHH Reservation App]
    A --> B[Frontend React App]
    A --> C[Backend Python App]
    B --> B1[Web Pages]
    B1 --> B1a[Home]
    B1 --> B1b[Booking/Reservation]
    B1 --> B1c[Menu]
    B1 --> B1d[About]
    B1 --> B1e[Online Order]
    B --> B2[UI Components]
    B --> B3[State Management]
    B --> B4[API Integration]
    C --> C1[Reservation Logic]
    C --> C2[Wait Time Calculation]
    C --> C3[User Data Management]
    C --> C4[Order Processing]
    C --> C5[Database Operations]
    A --> D[Database Firebase]
    D --> D1[User Data]
    D --> D2[Reservation Data]
    D --> D3[Order Data]