%% Overall System
    A[SHH Restaurant Website] --> B[Frontend React App]
    A --> D[Firebase Database]

%% Frontend Breakdown
    B --> B1[UI Components]
    B1 --> B1a[Home Page]
    B1a --> B2a[Wait time calculations]
    B1 --> B1b[Booking Page]
    B1b --> D2[Reservations Collection]
    B1 --> B1c[Menu Page]
    B1 --> B1d[About Page]
    B1 --> B1e[Login Page]
    B1e --> D1[User Data Collection]
    B1 --> B1f[Job Application Page]
    B1f --> D4[Job Applications Collection]

%% Firebase Breakdown
    D --> D1[User Data Collection]
    D --> D2[Reservations Collection]
    D --> D4[Job Applications Collection]
    D1 --> D1a[userId, Password]
    D2 --> D2a[Date, Time, Party Size]
    D4 --> D4a[Name, Phone, Position]