name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: |
        npm test
        npm run test -- --json --outputFile=test-results.json
      continue-on-error: false

    - name: Build Project
      run: npm run build
      
    - name: Check Build Artifacts
      run: |
        if [ ! -d "build" ]; then
          echo "Build directory is missing!"
          exit 1
        fi

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.json

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/