name: Reservation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Run tests and generate logs
      run: |
        node frontend/src/tests/createUserTest.js > createUserTest.log || true
        node frontend/src/tests/deleteUserTest.js > deleteUserTest.log || true
        node frontend/src/tests/bookingTest.js > bookingTest.log || true
        node frontend/src/tests/jobTest.js > jobTest.log || true
        node frontend/src/tests/headerTest.js > headerTest.log || true

    - name: Upload test logs
      uses: actions/upload-artifact@v3
      with:
        name: test-logs
        path: |
          createUserTest.log
          deleteUserTest.log
          bookingTest.log
          jobTest.log
          headerTest.log
